name: lug

services:

  db-postgres:
    # https://hub.docker.com/_/postgres
    image: "postgres:${PSQL_VERSION}-alpine"
    ports:
      - "5400:5432"
    restart: "unless-stopped"
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: "${PSQL_ROOT_USER_PASS}"
      POSTGRES_USER: "${PSQL_ROOT_USER_NAME}"
      POSTGRES_DB: "${PSQL_ROOT_DB}"
      POSTGRES_INITDB_ARGS: "--auth=${PSQL_AUTH_METHOD}"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - "vol-postgres:/var/lib/postgresql/data"

  mb-kafka-broker-1:
    # https://hub.docker.com/r/apache/kafka
    image: "apache/kafka:${KAFKA_VERSION}"
    ports:
      - "${KAFKA_BROKER_1_PORT}:9091"
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: "5m"
      start_interval: "2s"
      timeout: "3s"
      retries: "3"
      start_period: "30s"
    networks:
      default:
        aliases:
          - "kafka-broker-1"
    # If overriding ANY configuration, then NONE of the default configurations will be used.
    environment:
      KAFKA_CLUSTER_ID: "a2Fma2EtYnJva2VyLTEK" # echo "kafka-broker-1" | base64
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "EXTERNAL://:9091,INTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:${KAFKA_BROKER_1_PORT},INTERNAL://kafka-broker-1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker-1:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_NUM_PARTITIONS: "2"
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
    working_dir: "/opt/kafka/bin"
    volumes:
      - "vol-kafka-broker-1:/var/lib/kafka/data"

volumes:
  vol-postgres:
  vol-kafka-broker-1:
